=== AccessGlobal/VBA-Code/blob/Archivos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Archivos" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Archivos">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Id" index-key="Num " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="itgABaLCBE614DujMWI5sA==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACK2AAFosIETrXgO6MxYjmwAAAAAEMHcZ1wGeZAAAAAAAAAAABBAHIA
YwBoAGkAdgBvAHMAAAAAAAAA4Tdg3PsmZ0eDxPUuDTMB9gcAAACK2AAFosIETrXg
O6MxYjmwTgB1AG0AAAAAAAAAyObSzmO0kEGBwEMZxtv4dAcAAACK2AAFosIETrXg
O6MxYjmwVABpAHAAbwAAAAAAAADUGKn8B2pNR6eoY7blZMXlBwAAAIrYAAWiwgRO
teA7ozFiObBOAG8AbQBiAHIAZQBBAHIAYwBoAGkAdgBvAAAAAAAAADYDn+KoUmBA
imNA8V981wAHAAAAitgABaLCBE614DujMWI5sEYAaQBsAGUAXwBVAFIATAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Num" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4Tdg3PsmZ0eDxPUuDTMB9g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Tipo" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="yObSzmO0kEGBwEMZxtv4dA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="NombreArchivo" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="1Bip/AdqTUenqGO25WTF5Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3000"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="File_URL" minOccurs="0" od:jetType="hyperlink" od:sqlSType="ntext" od:hyperlink="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="NgOf4qhSYECKY0DxX3zXAA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="13845"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== AccessGlobal/VBA-Code/blob/Archivos.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Archivos.xsd" generated="2023-12-14T15:41:42">
<Archivos>
<Num>1</Num>
<Tipo>2</Tipo>
<NombreArchivo>Fechas_semana.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Fechas_semana/Fechas_semana.vba</File_URL>
</Archivos>
<Archivos>
<Num>28</Num>
<Tipo>2</Tipo>
<NombreArchivo>SendHTMLEmail.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20envío%20correo%20HTML/SendHTMLEmail.vba</File_URL>
</Archivos>
<Archivos>
<Num>29</Num>
<Tipo>2</Tipo>
<NombreArchivo>KillAccess.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Kill%20Access/KillAccess.vba</File_URL>
</Archivos>
<Archivos>
<Num>32</Num>
<Tipo>2</Tipo>
<NombreArchivo>Ocultar_Access.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Ocultar_Access/Ocultar_Access.vba</File_URL>
</Archivos>
<Archivos>
<Num>33</Num>
<Tipo>2</Tipo>
<NombreArchivo>Bloquear_cerrar_Access.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Bloquear_cerrar_access/Bloquear_cerrar_Access.vba</File_URL>
</Archivos>
<Archivos>
<Num>35</Num>
<Tipo>2</Tipo>
<NombreArchivo>Ocultar_maximizar.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Ocultar_maximizar/Ocultar_maximizar.vba</File_URL>
</Archivos>
<Archivos>
<Num>40</Num>
<Tipo>2</Tipo>
<NombreArchivo>AS_EsBisiesto.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/AS_EsBisiesto/AS_EsBisiesto.vba</File_URL>
</Archivos>
<Archivos>
<Num>43</Num>
<Tipo>2</Tipo>
<NombreArchivo>Minicalendario.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Minicalendario/Minicalendario.vba</File_URL>
</Archivos>
<Archivos>
<Num>44</Num>
<Tipo>2</Tipo>
<NombreArchivo>Mod_Efectos_Forms.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Efectos%20Forms/Mod_Efectos_Forms.vba</File_URL>
</Archivos>
<Archivos>
<Num>44</Num>
<Tipo>2</Tipo>
<NombreArchivo>Mod_Form_Efectos.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Efectos%20Forms/Mod_Form_Efectos.vba</File_URL>
</Archivos>
<Archivos>
<Num>50</Num>
<Tipo>2</Tipo>
<NombreArchivo>Estado Formulario.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Estado%20formulario/Estado Formulario.vba</File_URL>
</Archivos>
<Archivos>
<Num>70</Num>
<Tipo>2</Tipo>
<NombreArchivo>Mover formulario.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Mover_formulario/Mover formulario.vba</File_URL>
</Archivos>
<Archivos>
<Num>71</Num>
<Tipo>2</Tipo>
<NombreArchivo>Destello_Freefile.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Freefile/Destello_Freefile.vba</File_URL>
</Archivos>
<Archivos>
<Num>72</Num>
<Tipo>2</Tipo>
<NombreArchivo>Destello_WhatsApp.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20WhatsApp/Destello_WhatsApp.vba</File_URL>
</Archivos>
<Archivos>
<Num>74</Num>
<Tipo>2</Tipo>
<NombreArchivo>Destello _CheckInternet.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20CheckInternet/Destello _CheckInternet.vba</File_URL>
</Archivos>
<Archivos>
<Num>79</Num>
<Tipo>2</Tipo>
<NombreArchivo>posForm.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Posicionar_form/posForm.vba</File_URL>
</Archivos>
<Archivos>
<Num>82</Num>
<Tipo>2</Tipo>
<NombreArchivo>Sonido_en_App.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Sonido_en_App/Sonido_en_App.vba</File_URL>
</Archivos>
<Archivos>
<Num>83</Num>
<Tipo>2</Tipo>
<NombreArchivo>Mod_mouse.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Modificar_ratón/Mod_mouse.vba</File_URL>
</Archivos>
<Archivos>
<Num>84</Num>
<Tipo>2</Tipo>
<NombreArchivo>Cabecera_modulo.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Cabecera%20modulo/Cabecera_modulo.vba</File_URL>
</Archivos>
<Archivos>
<Num>86</Num>
<Tipo>2</Tipo>
<NombreArchivo>CambioHorario.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Cambio%20horario/CambioHorario.vba</File_URL>
</Archivos>
<Archivos>
<Num>90</Num>
<Tipo>2</Tipo>
<NombreArchivo>Emoticonos.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Emoticonos/Emoticonos.vba</File_URL>
</Archivos>
<Archivos>
<Num>93</Num>
<Tipo>2</Tipo>
<NombreArchivo>Pluralize.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Pluralize/Pluralize.vba</File_URL>
</Archivos>
<Archivos>
<Num>94</Num>
<Tipo>2</Tipo>
<NombreArchivo>Listbox_MultiSelect.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20ListBox%20selección%20múltiple/Listbox_MultiSelect.vba</File_URL>
</Archivos>
<Archivos>
<Num>96</Num>
<Tipo>2</Tipo>
<NombreArchivo>SemanaFecha.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Semana%20fecha/SemanaFecha.vba</File_URL>
</Archivos>
<Archivos>
<Num>98</Num>
<Tipo>2</Tipo>
<NombreArchivo>Access habla.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20habla/Access habla.vba</File_URL>
</Archivos>
<Archivos>
<Num>109</Num>
<Tipo>2</Tipo>
<NombreArchivo>Ocultar_minimizar_Access.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Ocultar%20Minimizar%20Access/Ocultar_minimizar_Access.vba</File_URL>
</Archivos>
<Archivos>
<Num>112</Num>
<Tipo>2</Tipo>
<NombreArchivo>Es_64_bits.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Es%2064%20bits/Es_64_bits.vba</File_URL>
</Archivos>
<Archivos>
<Num>114</Num>
<Tipo>2</Tipo>
<NombreArchivo>Hora_decimal.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Hora%20decimal/Hora_decimal.vba</File_URL>
</Archivos>
<Archivos>
<Num>120</Num>
<Tipo>2</Tipo>
<NombreArchivo>ShellExecute.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20ShellExecute/ShellExecute.vba</File_URL>
</Archivos>
<Archivos>
<Num>129</Num>
<Tipo>2</Tipo>
<NombreArchivo>FiltroForm_formulario.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Filtros%20por%20form/FiltroForm_formulario.vba</File_URL>
</Archivos>
<Archivos>
<Num>129</Num>
<Tipo>2</Tipo>
<NombreArchivo>FiltroForm_modulo.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Filtros%20por%20form/FiltroForm_modulo.vba</File_URL>
</Archivos>
<Archivos>
<Num>130</Num>
<Tipo>2</Tipo>
<NombreArchivo>CodigoPostalGoogle.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Codigo%20Postal%20Google/CodigoPostalGoogle.vba</File_URL>
</Archivos>
<Archivos>
<Num>131</Num>
<Tipo>2</Tipo>
<NombreArchivo>DistanciaCoordenadas.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Distancia%20entre%20coordenadas/DistanciaCoordenadas.vba</File_URL>
</Archivos>
<Archivos>
<Num>132</Num>
<Tipo>2</Tipo>
<NombreArchivo>Pitagoras.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Distancia%20Pitagoras/Pitagoras.vba</File_URL>
</Archivos>
<Archivos>
<Num>133</Num>
<Tipo>2</Tipo>
<NombreArchivo>Vicenty.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20distancia%20Vicenty/Vicenty.vba</File_URL>
</Archivos>
<Archivos>
<Num>135</Num>
<Tipo>2</Tipo>
<NombreArchivo>PausarCodigo.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Pausar%20codigo/PausarCodigo.vba</File_URL>
</Archivos>
<Archivos>
<Num>140</Num>
<Tipo>2</Tipo>
<NombreArchivo>Form_redondo.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Form%20redondo/Form_redondo.vba</File_URL>
</Archivos>
<Archivos>
<Num>143</Num>
<Tipo>2</Tipo>
<NombreArchivo>Exporta Excel.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Exporta%20Excel/Exporta Excel.vba</File_URL>
</Archivos>
<Archivos>
<Num>147</Num>
<Tipo>2</Tipo>
<NombreArchivo>SoloNumeros.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Sólo%20números/SoloNumeros.vba</File_URL>
</Archivos>
<Archivos>
<Num>148</Num>
<Tipo>2</Tipo>
<NombreArchivo>Enviar_a_papelera.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Enviar%20a%20papelera/Enviar_a_papelera.vba</File_URL>
</Archivos>
<Archivos>
<Num>149</Num>
<Tipo>2</Tipo>
<NombreArchivo>CapturaPantalla.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Captura%20Pantalla/CapturaPantalla.vba</File_URL>
</Archivos>
<Archivos>
<Num>150</Num>
<Tipo>2</Tipo>
<NombreArchivo>RecuperaPapelera.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20Recupera%20papelera/RecuperaPapelera.vba</File_URL>
</Archivos>
<Archivos>
<Num>151</Num>
<Tipo>2</Tipo>
<NombreArchivo>GetCapsLock.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20GetCapsLock/GetCapsLock.vba</File_URL>
</Archivos>
<Archivos>
<Num>152</Num>
<Tipo>2</Tipo>
<NombreArchivo>GetAttr.vba</NombreArchivo>
<File_URL>#https://github.com/AccessGlobal/VBA-Code/raw/main/Destello%20GetAttr/GetAttr.vba</File_URL>
</Archivos>
<Archivos>
<Num>157</Num>
