=== AccessGlobal/VBA-Code/blob/Articulos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Articulos" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Articulos">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Tipo Num " primary="yes" unique="yes" clustered="no" order="asc asc"/>
<od:tableProperty name="GUID" type="9" value="sVCnsmN7UEuo6L4v6/cSsQ==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACxUKeyY3tQS6jovi/r9xKxAAAAACJwrk16GeZAAAAAAAAAAABBAHIA
dABpAGMAdQBsAG8AcwAAAAAAAADMI/NZOZxHTK5bicqu0Yz/BwAAALFQp7Jje1BL
qOi+L+v3ErFUAGkAcABvAAAAAAAAAOMxW4S+aqhDhEDBdOYXAK8HAAAAsVCnsmN7
UEuo6L4v6/cSsU4AdQBtAAAAAAAAAOzmLbh0NlxKt4VkJw21rugHAAAAsVCnsmN7
UEuo6L4v6/cSsVQAaQB0AHUAbABvAAAAAAAAAO+/PRr3+P1MkdvMNazYX0kHAAAA
sVCnsmN7UEuo6L4v6/cSsUEAcgB0AGkAYwB1AGwAbwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Tipo" minOccurs="1" od:jetType="byte" od:sqlSType="tinyint" od:nonNullable="yes" type="xsd:unsignedByte">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="zCPzWTmcR0yuW4nKrtGM/w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Num" minOccurs="1" od:jetType="integer" od:sqlSType="smallint" od:nonNullable="yes" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4zFbhL5qqEOEQMF05hcArw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Titulo" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="7OYtuHQ2XEq3hWQnDbWu6A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Articulo" minOccurs="0" od:jetType="hyperlink" od:sqlSType="ntext" od:hyperlink="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="7789Gvf4/UyR28w1rNhfSQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== AccessGlobal/VBA-Code/blob/Articulos.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Articulos.xsd" generated="2023-11-29T20:11:03">
<Articulos>
<Tipo>1</Tipo>
<Num>1</Num>
<Titulo>MasterClass ListBox dinámicos:</Titulo>
<Articulo>#https://access-global.net/listbox-dinamicos/#</Articulo>
</Articulos>
<Articulos>
<Tipo>1</Tipo>
<Num>2</Num>
<Titulo>MasterClass Drag&amp;Drop:</Titulo>
<Articulo>#https://access-global.net/drag-drop-en-access#</Articulo>
</Articulos>
<Articulos>
<Tipo>1</Tipo>
<Num>3</Num>
<Titulo>MasterClass MsgBox personalizado:</Titulo>
<Articulo>#https://access-global.net/msgbox-personalizado/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>1</Num>
<Titulo>Destello Fechas semana:</Titulo>
<Articulo>#https://access-global.net/obtener-la-fecha-del-primer-dia-de-la-semana-o-ultimo-dia-de-la-semana-en-access-vba/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>28</Num>
<Titulo>Destello envío correo HTML:</Titulo>
<Articulo>#https://access-global.net/diseno-enviar-bonitos-correos-en-html/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>29</Num>
<Titulo>Destello Kill Access:</Titulo>
<Articulo>#https://access-global.net/access-kill-access#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>32</Num>
<Titulo>Destello Ocultar Access:</Titulo>
<Articulo>#https://access-global.net/access-ocultar-access/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>33</Num>
<Titulo>Destello Bloquear cerrar access:</Titulo>
<Articulo>#https://access-global.net/bloquear-cerrar-access/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>35</Num>
<Titulo>Destello Ocultar maximizar:</Titulo>
<Articulo>#https://access-global.net/ocultar-maximizar-access/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>40</Num>
<Titulo>AS EsBisiesto:</Titulo>
<Articulo>#https://access-global.net/saber-si-un-ano-es-bisiesto/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>43</Num>
<Titulo>Destello Minicalendario:</Titulo>
<Articulo>#https://access-global.net/access-minicalendario/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>44</Num>
<Titulo>Destello Efectos Forms:</Titulo>
<Articulo>#https://access-global.net/diseno-efectos-ventana/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>50</Num>
<Titulo>Destello Estado formulario:</Titulo>
<Articulo>#https://access-global.net/vba-estado-de-un-formulario/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>70</Num>
<Titulo>Destello Mover formulario:</Titulo>
<Articulo>#https://access-global.net/diseno-mover-formulario#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>71</Num>
<Titulo>Destello Freefile:</Titulo>
<Articulo>#https://access-global.net/vba-freefile-function#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>72</Num>
<Titulo>Destello WhatsApp:</Titulo>
<Articulo>#https://access-global.net/vba-sencilla-forma-de-enviar-mensaje-de-whatsapp#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>74</Num>
<Titulo>Destello CheckInternet:</Titulo>
<Articulo>#https://access-global.net/vba-tengo-conexion-a-internet#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>79</Num>
<Titulo>Destello Posicionar form:</Titulo>
<Articulo>#https://access-global.net/access-redimensionar-y-posicionar-formulario#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>82</Num>
<Titulo>Destello Sonido en App:</Titulo>
<Articulo>#https://access-global.net/vba-sonido-en-mi-app#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>83</Num>
<Titulo>Destello Modificar ratón:</Titulo>
<Articulo>#https://access-global.net/diseno-crea-tu-propio-icono-de-raton#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>84</Num>
<Titulo>Destello Cabecera modulo:</Titulo>
<Articulo>#https://access-global.net/vba-cabecera-de-modulo#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>86</Num>
<Titulo>Destello Cambio horario:</Titulo>
<Articulo>#https://access-global.net/vba-horario-de-verano#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>90</Num>
<Titulo>Destello Emoticonos:</Titulo>
<Articulo>#https://access-global.net/diseno-utiliza-emoticonos-en-tus-aplicaciones#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>93</Num>
<Titulo>Destello Pluralize:</Titulo>
<Articulo>#https://access-global.net/vba-funcion-pluralize-by-mike-wolfe/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>94</Num>
<Titulo>Destello ListBox selección múltiple:</Titulo>
<Articulo>#https://access-global.net/access-cuadro-de-lista-con-seleccion-multiple/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>96</Num>
<Titulo>Destello Semana fecha:</Titulo>
<Articulo>#https://access-global.net/vba-en-que-semana-estamos#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>97</Num>
<Titulo>Destello función StrPtr:</Titulo>
<Articulo>#https://access-global.net/vba-controlar-respuesta-inputbox/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>98</Num>
<Titulo>Destello habla:</Titulo>
<Articulo>#https://access-global.net/access-que-te-lo-diga-access#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>109</Num>
<Titulo>Destello Ocultar Minimizar Access:</Titulo>
<Articulo>#https://access-global.net/vba-ocultar-minimizar-access/#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>112</Num>
<Titulo>Destello Es 64 bits:</Titulo>
<Articulo>#https://access-global.net/vba-es-accde#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>114</Num>
<Titulo>Destello Hora decimal:</Titulo>
<Articulo>#https://access-global.net/vba-convertir-hora-en-decimal#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>120</Num>
<Titulo>Destello ShellExecute:</Titulo>
<Articulo>#https://access-global.net/vba-shellexecute#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>129</Num>
<Titulo>Destello Filtros por form:</Titulo>
<Articulo>#https://access-global.net/vba-gestionamos-el-filtro-por-formulario#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>130</Num>
<Titulo>Destello Codigo Postal Google:</Titulo>
<Articulo>#https://access-global.net/vba-conocer-codigo-postal-y-coordenadas-con-la-api-de-google-maps#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>131</Num>
<Titulo>Destello Distancia entre coordenadas:</Titulo>
<Articulo>#https://access-global.net/vba-google-maps-api-calcular-la-distancia-entre-dos-coordenadas#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>132</Num>
<Titulo>Destello Distancia Pitagoras:</Titulo>
<Articulo>#https://access-global.net/vba-google-maps-api-calcular-la-distancia-entre-dos-coordenadas-pitagoras#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>133</Num>
<Titulo>Destello distancia Vicenty:</Titulo>
<Articulo>#https://access-global.net/vba-google-maps-api-calcular-la-distancia-entre-dos-coordenadas-vincenty#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>135</Num>
<Titulo>Destello Pausar codigo:</Titulo>
<Articulo>#https://access-global.net/vba-la-forma-mas-eficiente-de-pausar-el-codigo#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>140</Num>
<Titulo>Destello Form redondo:</Titulo>
<Articulo>#https://access-global.net/diseno-formularios-redondos#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>143</Num>
<Titulo>Destello Exporta Excel:</Titulo>
<Articulo>#https://access-global.net/access-exportar-contenido-de-un-recordset-a-excel-copyfromrecordset#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>147</Num>
<Titulo>Destello Sólo números:</Titulo>
<Articulo>#https://access-global.net/vba-estas-obligado-a-escribir-solo-numeros#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>148</Num>
<Titulo>Destello Enviar a papelera:</Titulo>
<Articulo>#https://access-global.net/vba-enviar-fichero-a-la-papelera#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>149</Num>
<Titulo>Destello Captura Pantalla:</Titulo>
<Articulo>#https://access-global.net/vba-captura-de-pantalla#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>150</Num>
<Titulo>Destello Recupera papelera:</Titulo>
<Articulo>#https://access-global.net/vba-recuperar-el-fichero-enviado-a-la-papelera#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>151</Num>
<Titulo>Destello GetCapsLock:</Titulo>
<Articulo>#https://access-global.net/vba-detectar-capslock#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>152</Num>
<Titulo>Destello GetAttr:</Titulo>
<Articulo>#https://access-global.net/vba-getattr#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>157</Num>
<Titulo>Destello Ordenar formularios:</Titulo>
<Articulo>#https://access-global.net/vba-una-funcion-para-ordenar-todos-los-formularios#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>158</Num>
<Titulo>Destello Obtener IP pública:</Titulo>
<Articulo>#https://access-global.net/vba-obtener-mi-ip-publica#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>159</Num>
<Titulo>Destello Obtener IP local:</Titulo>
<Articulo>#https://access-global.net/vba-obtener-mi-ip-local#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>160</Num>
<Titulo>Destello Existe fichero:</Titulo>
<Articulo>#https://access-global.net/vba-metodo-fileexists#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>161</Num>
<Titulo>Destello Existe carpeta:</Titulo>
<Articulo>#https://access-global.net/vba-metodo-folderexists#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>162</Num>
<Titulo>Destello ParentFolder:</Titulo>
<Articulo>#https://access-global.net/vba-metodo-GetParentFolderName#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>163</Num>
<Titulo>Destello GetExtensioName:</Titulo>
<Articulo>#https://access-global.net/vba-metodo-GetExtensionName#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>164</Num>
<Titulo>Destello Construir ruta:</Titulo>
<Articulo>#https://access-global.net/vba-metodo-BuildPath#</Articulo>
</Articulos>
<Articulos>
<Tipo>2</Tipo>
<Num>165</Num>
